[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=breeze-dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x12\0M\0\x65\0s\0l\0o\0L\0G\0S\0 \0N\0F@$\0\0\0\0\0\0\0\0\0\x0e\xfe\0\x0f\0\0\x10\x2e)
general=@Variant(\0\0\0@\0\0\0\x12\0M\0\x65\0s\0l\0o\0L\0G\0S\0 \0N\0F@$\0\0\0\0\0\0\0\0\0\x0e\xfe\0\x0f\0\0\x10\x2e)
